Repository kaito-project/kaito, pull requests merged in 2025-05, with the labels that each got.

#1091 feat: Deprecate Llama 2 Models and Add Llama3
  .github/actions/e2e-base-setup/action.yml
  .github/dependabot.yml
  .github/e2e-preset-configs.json
  api/v1beta1/workspace_types.go
  cmd/workspace/models.go
  docker/presets/models/llama-2/Dockerfile
  docker/presets/models/llama-2/Dockerfile.dockerignore
  examples/inference/kaito_workspace_llama-3.1_8b_instruct.yaml
  examples/inference/kaito_workspace_llama2_13b-chat.yaml
  examples/inference/kaito_workspace_llama2_13b.yaml
  examples/inference/kaito_workspace_llama2_70b-chat.yaml
  examples/inference/kaito_workspace_llama2_7b-chat.yaml
  examples/inference/kaito_workspace_llama2_7b.yaml
  pkg/model/interface.go
  presets/README.md
  presets/workspace/inference/chat_templates/llama-2-chat.jinja
  presets/workspace/inference/llama2-chat/inference_api.py
  presets/workspace/inference/llama2-completion/inference_api.py
  presets/workspace/models/llama2/README.md
  presets/workspace/models/llama2/model.go
  presets/workspace/models/llama2chat/README.md
  presets/workspace/models/llama2chat/model.go
  presets/workspace/models/llama3/README.md
  presets/workspace/models/llama3/model.go
  presets/workspace/models/supported_models.yaml
  presets/workspace/test/manifests/llama-2-13b-chat/llama-2-13b-chat.yaml
  presets/workspace/test/manifests/llama-2-13b/llama-2-13b.yaml
  presets/workspace/test/manifests/llama-2-7b-chat/llama-2-7b-chat.yaml
  presets/workspace/test/manifests/llama-2-7b/llama-2-7b.yaml
  test/e2e/preset_test.go
  test/e2e/preset_vllm_test.go
Labels: Review effort 4/5

#1086 feat: strip managed fields for controller informer
  cmd/ragengine/main.go
  cmd/workspace/main.go
Labels: Review effort 2/5

#1094 fix: change ephemeral storage to resource storage in nodeclaim
  pkg/utils/nodeclaim/nodeclaim.go
Labels: Review effort 2/5

#1095 feat: Update pipeline to handle downloadAtRuntime models
  .github/workflows/kind-cluster/determine_models.py
  .github/workflows/preset-image-build-1ES.yml
  presets/workspace/models/llama3/README.md
  presets/workspace/models/llama3/model.go
  presets/workspace/models/supported_models.yaml
  test/e2e/preset_test.go
Labels: Review effort 3/5

#1098 fix: update GPUMemGB for Standard_ND96amsr_A100_v4
  pkg/sku/azure_sku_handler.go
Labels: Review effort 1/5

#1096 fix: Troubleshooting Target Modules Error
  docs/tuning/README.md
Labels: Review effort 2/5

#1092 docs: add proposal for distributed inference
  .github/workflows/markdown-link-check.yml
  CODE_OF_CONDUCT.md
  README.md
  docs/proposals/20250325-distributed-inference.md
  hack/go-install.sh
Labels: Review effort 4/5

#1100 feat: Cleanup Deprecated ImageAccess Field
  .github/workflows/preset-image-build.yml
  api/v1beta1/workspace_types.go
  api/v1beta1/workspace_validation.go
  api/v1beta1/workspace_validation_test.go
  charts/kaito/workspace/crds/kaito.sh_workspaces.yaml
  config/crd/bases/kaito.sh_workspaces.yaml
  pkg/workspace/inference/preset-inferences.go
  pkg/workspace/tuning/preset-tuning.go
  pkg/workspace/tuning/preset-tuning_test.go
  presets/workspace/inference/chat_templates/phi-4.jinja
  presets/workspace/models/deepseek/model.go
  presets/workspace/models/falcon/model.go
  presets/workspace/models/llama3/model.go
  presets/workspace/models/mistral/model.go
  presets/workspace/models/phi2/model.go
  presets/workspace/models/phi3/model.go
  presets/workspace/models/phi4/model.go
  presets/workspace/models/qwen/model.go
  test/e2e/preset_test.go
  test/e2e/preset_vllm_test.go
  test/e2e/utils/utils.go
  test/e2e/webhook_test.go
  test/rage2e/rag_test.go
Labels: Review effort 3/5

#1102 feat: Ensure shm volume added
  pkg/ragengine/controllers/preset-rag.go
  pkg/utils/common-preset.go
  pkg/workspace/controllers/workspace_controller.go
  pkg/workspace/inference/preset-inferences.go
  pkg/workspace/tuning/preset-tuning.go
Labels: Review effort 3/5

#1108 chore: remove torchrun and distributed inference references
  Makefile
  pkg/model/interface.go
  pkg/utils/test/testModel.go
  pkg/workspace/inference/preset-inference-types.go
  pkg/workspace/inference/preset-inferences.go
  pkg/workspace/inference/preset-inferences_test.go
  pkg/workspace/manifests/manifests.go
  pkg/workspace/tuning/preset-tuning.go
  pkg/workspace/tuning/preset-tuning_test.go
  presets/workspace/models/deepseek/model.go
  presets/workspace/models/falcon/model.go
  presets/workspace/models/llama3/model.go
  presets/workspace/models/mistral/model.go
  presets/workspace/models/phi2/model.go
  presets/workspace/models/phi3/model.go
  presets/workspace/models/phi4/model.go
  presets/workspace/models/qwen/model.go
Labels: Review effort 4/5

#1111 fix: update arc GPUMem to 32 and add more examples for arc
  examples/inference/arc-examples/kaito_workspace_deepseek_r1_distill_llama_8b_with_customized_config.yaml
  examples/inference/arc-examples/kaito_workspace_phi_4_mini.yaml
  examples/inference/arc-examples/kaito_workspace_qwen_2.5_coder_7b-instruct.yaml
  pkg/sku/arc_sku_handker.go
Labels: Review effort 3/5

#1097 feat: update GPU provisioner version and model OS disk storage
  Makefile
  docs/installation.md
  pkg/model/interface.go
  pkg/ragengine/controllers/ragengine_controller.go
  pkg/workspace/controllers/workspace_controller.go
  presets/workspace/models/deepseek/model.go
  presets/workspace/models/falcon/model.go
  presets/workspace/models/llama3/model.go
  presets/workspace/models/mistral/model.go
  presets/workspace/models/phi2/model.go
  presets/workspace/models/phi3/model.go
  presets/workspace/models/phi4/model.go
  presets/workspace/models/qwen/model.go
  terraform/variables.tf
Labels: Review effort 4/5

#1116 chore: update tool chat templates
  presets/workspace/inference/chat_templates/tool-chat-hermes.jinja
  presets/workspace/inference/chat_templates/tool-chat-llama3.1-json.jinja
  presets/workspace/inference/chat_templates/tool-chat-mistral.jinja
  presets/workspace/inference/chat_templates/tool-chat-phi4-mini.jinja
Labels: Review effort 4/5

#1103 test: Add E2E test for new Llama Model
  .github/workflows/e2e-workflow.yml
  .github/workflows/workspace-e2e.yml
  presets/workspace/models/llama3/model.go
  test/e2e/preset_test.go
  test/e2e/preset_vllm_test.go
  test/e2e/utils/utils.go
  test/e2e/webhook_test.go
  test/rage2e/rag_test.go
Labels: Review effort 4/5

#1105 docs: expand on container probes in 20250325-distributed-inference.md
  docs/proposals/20250325-distributed-inference.md
Labels: Review effort 4/5

#1117 feat: bump service image to 0.1.1
  .github/actions/build-image-action/action.yml
  .github/workflows/preset-image-build.yml
  docker/presets/models/tfs/Dockerfile
  pkg/workspace/inference/preset-inferences_test.go
  presets/workspace/models/supported_models.yaml
Labels: Review effort 3/5

#1125 docs: add tool calling example
  .github/workflows/e2e-workflow.yml
  .github/workflows/workspace-e2e.yml
  examples/inference/kaito_workspace_tool_calling.yaml
Labels: Review effort 3/5

#1120 fix: remove PYTORCH_CUDA_ALLOC_CONF environment variable
  pkg/workspace/inference/preset-inferences_test.go
  pkg/workspace/manifests/manifests.go
Labels: Review effort 3/5

#1062 fix: move nodeclaim check to right place
  pkg/ragengine/controllers/ragengine_controller.go
  pkg/utils/nodeclaim/nodeclaim.go
  pkg/utils/nodeclaim/nodeclaim_test.go
  pkg/workspace/controllers/workspace_controller.go
  pkg/workspace/controllers/workspace_controller_test.go
Labels: Review effort 3/5

#1126 release: update manifest and helm charts for v0.4.6
  Makefile
  README.md
  charts/kaito/workspace/Chart.yaml
  charts/kaito/workspace/README.md
  charts/kaito/workspace/values.yaml
  docs/installation.md
  terraform/variables.tf
Labels: Review effort 2/5

#1127 Intro project governance page
  GOVERNANCE.md
Labels: Review effort 2/5

#1128 feat: update gpu-provisioner version to v0.3.5 for kaito
  Makefile
  docs/installation.md
  terraform/variables.tf
Labels: Review effort 1/5

#1087 chore: merge dependabot pr into groups
  .github/dependabot.yml
Labels: Review effort 3/5

#1114 feat: adding metadata filtering on list documents api
  presets/ragengine/main.py
  presets/ragengine/tests/api/test_main.py
  presets/ragengine/tests/vector_store/test_base_store.py
  presets/ragengine/vector_store/base.py
  presets/ragengine/vector_store_manager/manager.py
Labels: Review effort 4/5

#949 feat: support multi-node distributed inference for vLLM
  api/v1beta1/workspace_validation.go
  api/v1beta1/workspace_validation_test.go
  docker/presets/models/tfs/Dockerfile
  pkg/model/interface.go
  pkg/utils/common.go
  pkg/utils/common_test.go
  pkg/utils/test/testModel.go
  pkg/workspace/inference/preset-inference-types.go
  pkg/workspace/inference/preset-inferences.go
  pkg/workspace/inference/preset-inferences_test.go
  pkg/workspace/manifests/manifests.go
  presets/workspace/dependencies/requirements.txt
  presets/workspace/inference/vllm/multi-node-health-check.py
  presets/workspace/models/supported_models.yaml
Labels: Review effort 4/5

#1138 feat: bump base image to 0.0.3
  .github/e2e-preset-configs.json
  .github/workflows/e2e-preset-test.yml
  .github/workflows/e2e-preset-tuning-test.yml
  presets/workspace/models/supported_models.yaml
  presets/workspace/test/manifests/vllm-distributed/vllm-distributed.yaml
Labels: Review effort 4/5

#1144 fix: customize gpu-provisioner deployment name for e2e test
  Makefile
  test/e2e/e2e_test.go
  test/rage2e/e2e_test.go
Labels: Review effort 3/5

#1118 feat: support volume for tuning
  api/v1alpha1/workspace_validation.go
  api/v1beta1/workspace_validation.go
  charts/kaito/workspace/templates/lora-params.yaml
  charts/kaito/workspace/templates/qlora-params.yaml
  docs/tuning/README.md
  examples/fine-tuning/kaito_workspace_tuning_phi_3_with_pvc_volume.yaml
  pkg/utils/common-preset.go
  pkg/workspace/manifests/manifests.go
  pkg/workspace/tuning/preset-tuning.go
  pkg/workspace/tuning/preset-tuning_test.go
  presets/workspace/tuning/text-generation/fine_tuning.py
Labels: Review effort 4/5
