Repository kaito-project/kaito, pull requests merged in 2025-08, with the labels that each got.

#1341 chore: update node sku for e2e tests
  .github/actions/e2e-base-setup/action.yml
  .github/workflows/e2e-workflow.yml
  .github/workflows/ragengine-e2e-workflow.yml
  Makefile
  pkg/sku/azure_sku_handler.go
  test/e2e/preset_test.go
  test/e2e/preset_vllm_test.go
  test/rage2e/rag_test.go
Labels: Review effort 2/5

#1342 chore: Revert the model used in the rag e2e test back to Phi-3
  test/rage2e/rag_test.go
Labels: Review effort 4/5

#1251 feat: add deepseek-r1/deepseek-v3 model
  charts/kaito/workspace/templates/supported-models-configmap.yaml
  examples/inference/kaito_workspace_deepseek_r1.yaml
  examples/inference/kaito_workspace_deepseek_v3.yaml
  pkg/workspace/inference/preset-inferences.go
  presets/workspace/inference/chat_templates/tool-chat-deepseekr1.jinja
  presets/workspace/inference/chat_templates/tool-chat-deepseekv3.jinja
  presets/workspace/models/deepseek/README.md
  presets/workspace/models/deepseek/model.go
  presets/workspace/models/llama3/README.md
  presets/workspace/models/supported_models.yaml
  website/docs/multi-node-inference.md
  website/docs/tool-calling.md
Labels: Review effort 3/5

#1347 chore: fix references to yaml files and rename bugs
  .github/actions/build-image-action/action.yaml
  .github/actions/build-image-action/action.yml
  .github/actions/e2e-base-setup/action.yaml
  .github/actions/e2e-base-setup/action.yml
  .github/workflows/deploy-docs.yaml
  .github/workflows/markdown-link-check.yaml
  .github/workflows/publish-rag-controller-gh-image.yaml
  .github/workflows/publish-rag-service-gh-image.yaml
  .github/workflows/publish-workspace-gh-image.yaml
  .github/workflows/ragengine-e2e.yaml
  .github/workflows/workspace-e2e.yaml
Labels: Review effort 2/5

#1338 fix: fix bug where fetch GPU count was failing and defaulting
  pkg/utils/common.go
  pkg/utils/common_test.go
  pkg/workspace/inference/preset-inferences_test.go
Labels: Review effort 3/5

#1334 docs: add chat/completions rag docs and split install/api docs
  website/docs/rag-api.md
  website/docs/rag.md
  website/sidebars.js
Labels: Review effort 3/5

#1364 chore: bump base image to 0.0.5
  .github/actions/build-image-action/action.yaml
  .github/e2e-preset-configs.json
  .github/workflows/e2e-preset-test.yaml
  charts/kaito/workspace/templates/supported-models-configmap.yaml
  presets/workspace/models/supported_models.yaml
  presets/workspace/test/manifests/inference-tmpl/manifest.yaml
Labels: Review effort 3/5

#1365 docs: fix EKS hyperlink
  website/versioned_docs/version-v0.5.0/installation.md
  website/versioned_docs/version-v0.5.1/installation.md
Labels: Review effort 1/5

#1391 docs: corrected typo in README.md
  README.md
Labels: Review effort 1/5

#1326 feat: offload kv cache to cpu RAM on vllm v1
  presets/workspace/dependencies/requirements.txt
  presets/workspace/inference/vllm/inference_api.py
  presets/workspace/inference/vllm/tests/test_vllm_inference_api.py
Labels: Review effort 3/5

#1395 ci: aikit test
  .github/workflows/aikit.yaml
Labels: Review effort 4/5

#1252 feat: Add Gateway API Inference Extension support
  .github/actions/e2e-base-setup/action.yaml
  .github/workflows/e2e-workflow.yaml
  .github/workflows/ragengine-e2e-workflow.yaml
  Makefile
  Tiltfile
  charts/kaito/workspace/Chart.yaml
  charts/kaito/workspace/crds/inference.networking.x-k8s.io_inferencemodels.yaml
  charts/kaito/workspace/crds/inference.networking.x-k8s.io_inferencepools.yaml
  charts/kaito/workspace/templates/_helpers.tpl
  charts/kaito/workspace/templates/clusterrole.yaml
  charts/kaito/workspace/values.yaml
  cmd/workspace/main.go
  go.mod
  go.sum
  pkg/featuregates/featuregates.go
  pkg/utils/common.go
  pkg/utils/common_test.go
  pkg/utils/consts/consts.go
  pkg/utils/crd.go
  pkg/utils/resources/resources.go
  pkg/utils/resources/resources_test.go
  pkg/workspace/controllers/workspace_controller.go
  pkg/workspace/controllers/workspace_controller_test.go
  pkg/workspace/inference/preset_inferences.go
  pkg/workspace/manifests/manifests.go
  pkg/workspace/manifests/manifests_test.go
  pkg/workspace/tuning/preset_tuning.go
  test/e2e/preset_vllm_test.go
  test/e2e/utils/cluster.go
Labels: Review effort 4/5

#1404 feat: Enhanced Token Management and Context Selection for RAGEngine
  presets/ragengine/config.py
  presets/ragengine/inference/inference.py
  presets/ragengine/main.py
  presets/ragengine/requirements.txt
  presets/ragengine/tests/api/test_chat_completions.py
  presets/ragengine/tests/api/test_node_processing.py
  presets/ragengine/tests/vector_store/test_base_store.py
  presets/ragengine/vector_store/base.py
  presets/ragengine/vector_store/node_processors/__init__.py
  presets/ragengine/vector_store/node_processors/contex_selection_node_processor.py
  website/docs/rag-api.md
Labels: Review effort 4/5

#1415 fix: cannot read kv-cache-cpu-memory-utilization from ConfigMap
  charts/kaito/workspace/templates/inference-params.yaml
  presets/workspace/inference/vllm/inference_api.py
Labels: Review effort 2/5

#1405 chore: bump vLLM to 0.10.1
  .github/actions/e2e-base-setup/action.yaml
  .github/determine_models.py
  .github/workflows/e2e-workflow.yaml
  .github/workflows/preset-image-build-1ES.yaml
  .github/workflows/preset-image-build.yaml
  .github/workflows/workspace-e2e.yaml
  Makefile
  charts/kaito/workspace/crds/kaito.sh_workspaces.yaml
  charts/kaito/workspace/templates/supported-models-configmap.yaml
  pkg/model/interface.go
  pkg/model/interface_test.go
  pkg/utils/common_preset.go
  pkg/utils/common_preset_test.go
  pkg/workspace/inference/preset_inferences.go
  pkg/workspace/inference/preset_inferences_test.go
  pkg/workspace/manifests/manifests.go
  pkg/workspace/tuning/preset_tuning.go
  pkg/workspace/tuning/preset_tuning_test.go
  pkg/workspace/tuning/scripts/data-downloader.sh
  presets/workspace/dependencies/requirements.txt
  presets/workspace/inference/text-generation/tests/test_inference_api.py
  presets/workspace/inference/vllm/inference_api.py
  presets/workspace/models/deepseek/model.go
  presets/workspace/models/supported_models.yaml
Labels: Review effort 3/5

#1424 fix: add missing pynvml package dependency
  presets/workspace/dependencies/requirements.txt
Labels: Review effort 1/5

#1426 Revert "fix: add missing pynvml package dependency"
  presets/workspace/dependencies/requirements.txt
Labels: Review effort 1/5

#1417 feat: add nodeclaim manager for creating/deleting nodeclaims of workspace
  pkg/utils/nodeclaim/nodeclaim.go
  pkg/utils/nodeclaim/nodeclaim_test.go
  pkg/utils/resources/nodes.go
  pkg/utils/resources/nodes_test.go
  pkg/utils/workspace/workspace.go
  pkg/utils/workspace/workspace_test.go
  pkg/workspace/controllers/workspace_controller.go
  pkg/workspace/controllers/workspace_gc_finalizer.go
  pkg/workspace/controllers/workspace_status.go
  pkg/workspace/controllers/workspace_status_test.go
  pkg/workspace/resource/node_claim.go
  pkg/workspace/resource/node_claim_test.go
Labels: Review effort 4/5

#1429 fix: add nodeaffinity for tuning job
  pkg/workspace/tuning/preset_tuning.go
  pkg/workspace/tuning/preset_tuning_test.go
Labels: Review effort 2/5

#1438 docs: update benchmarks to use vLLM data for Phi 4 Mini and Llama 8B
  website/docs/gpu-benchmarks.md
  website/static/img/a10-itl.png
  website/static/img/a10-ttft.png
  website/static/img/llama-3.1-8b-itl.png
  website/static/img/llama-3.1-8b-ttft.png
  website/static/img/phi-4-mini-itl.png
  website/static/img/phi-4-mini-ttft.png
Labels: Review effort 3/5

#1445 docs: update aikit docs to fix links
  website/docs/aikit.md
  website/versioned_docs/version-v0.6.x/aikit.md
Labels: Review effort 1/5

#1448 fix：bump lmcache to 0.3.5
  presets/workspace/dependencies/requirements.txt
  presets/workspace/models/supported_models.yaml
Labels: Review effort 1/5

#1449 chore: bump kaito-base tag to 0.0.7
  charts/kaito/workspace/templates/supported-models-configmap.yaml
  presets/workspace/models/supported_models.yaml
Labels: Review effort 1/5

#1433 ci: update .github/dependabot.yaml with the right file paths
  .github/dependabot.yaml
Labels: Review effort 1/5

#1392 feat: [BREAKING] adding context size window to rag spec
  api/v1alpha1/ragengine_types.go
  api/v1alpha1/ragengine_validation.go
  api/v1alpha1/ragengine_validation_test.go
  charts/kaito/ragengine/crds/kaito.sh_ragengines.yaml
  config/crd/bases/kaito.sh_ragengines.yaml
  examples/RAG/kaito_ragengine_phi_3.yaml
  pkg/ragengine/manifests/manifests.go
  pkg/ragengine/manifests/manifests_test.go
  pkg/utils/test/test_utils.go
  test/rage2e/rag_test.go
Labels: Review effort 3/5

#1434 docs: add docs for Gateway API Inference Extension
  examples/gateway-api-inference-extension/destinationrule-mistral-7b-instruct.yaml
  examples/gateway-api-inference-extension/destinationrule-phi-4-mini-instruct.yaml
  examples/gateway-api-inference-extension/gateway.yaml
  examples/gateway-api-inference-extension/httproute-bbr.yaml
  examples/gateway-api-inference-extension/httproute.yaml
  website/docs/gateway-api-inference-extension.md
  website/sidebars.js
Labels: Review effort 2/5

#1446 fix: add nodeSelector on Linux to avoid crash on Windows node
  charts/kaito/workspace/templates/nvidia-device-plugin-ds.yaml
  charts/kaito/workspace/values.yaml
Labels: Review effort 2/5

#1427 feat: only run vector search on latest user message
  presets/ragengine/config.py
  presets/ragengine/inference/inference.py
  presets/ragengine/models.py
  presets/ragengine/tests/api/test_chat_completions.py
  presets/ragengine/vector_store/base.py
  presets/ragengine/vector_store/chat_completions_wrapper.md
Labels: Review effort 3/5
