Repository kaito-project/kaito, pull requests merged in 2025-07, with the labels that each got.

#1224 chore: bump local-csi-driver to 0.2.0
  Makefile
  charts/kaito/workspace/templates/local-csi-driver-ds.yaml
  charts/kaito/workspace/templates/local-csi-storageclass.yaml
  hack/local-csi-driver-charts-sync/local-csi-driver-charts-sync.sh
  hack/local-csi-driver-charts-sync/local-csi-driver-charts.diff
  test/e2e/preset_vllm_test.go
  test/e2e/utils/ginkgo.go
Labels: Review effort 3/5

#1232 release: update manifest and helm charts for v0.5.0
  Makefile
  README.md
  charts/kaito/ragengine/Chart.yaml
  charts/kaito/ragengine/README.md
  charts/kaito/ragengine/values.yaml
  charts/kaito/workspace/Chart.yaml
  charts/kaito/workspace/README.md
  charts/kaito/workspace/values.yaml
  terraform/variables.tf
  website/docs/installation.md
Labels: Review effort 2/5

#1235 fix: specify helm charts target in pipeline
  .github/workflows/publish-ragengine-helm-chart.yml
  .github/workflows/publish-workspace-helm-chart.yml
  .github/workflows/ragengine-e2e-workflow.yml
Labels: Review effort 3/5

#1227 chore: bump k8s.io/* deps -> v0.33.2, controller-runtime -> v0.21.0
  go.mod
  go.sum
  pkg/ragengine/controllers/ragengine_controller_test.go
  test/e2e/utils/cluster.go
Labels: Review effort 4/5

#1239 docs: add explanation for max-model-len requirement
  README.md
  examples/inference/kaito_workspace_llama-3.3_70b_instruct.yaml
  website/docs/intro.md
  website/docs/proposals/20250529-llama-3.3-70b-instruct.md
Labels: Review effort 3/5

#1250 docs: update owners
  CODEOWNERS
Labels: Review effort 1/5

#1237 docs: add keda scaler for kaito workloads proposal
  website/docs/proposals/20250704-keda-scaler-for-inference-workloads.md
  website/static/img/keda-kaito-scaler-arch.png
  website/static/img/keda-kaito-scaler.png
  website/static/img/keda-prometheus-auto-scaler.png
  website/static/img/keda-prometheus-cron-auto-scaler.png
Labels: Review effort 3/5

#1240 chore: bump terraform provider versions and add kaito-ragengine chart deployment
  terraform/.terraform.lock.hcl
  terraform/kaito.tf
  terraform/main.tf
  terraform/variables.tf
Labels: Review effort 3/5

#1255 docs: updage RAG Docs to remove rerank options
  website/docs/rag.md
Labels: Review effort 2/5

#1258 docs: update README.md
  README.md
  website/docs/intro.md
  website/docs/rag.md
  website/static/img/arch.png
  website/static/img/ragarch.png
  website/static/img/ragarch.svg
Labels: Review effort 3/5

#1259 fix: fix deploy-docs.yml
  .github/workflows/deploy-docs.yml
Labels: Review effort 2/5

#1266 fix doc error kaito.sh/enablelb should be True instead of true
  examples/README.md
Labels: Review effort 1/5

#1265 feat: expose kaito supported models via configmap
  .github/workflows/unit-tests.yml
  Makefile
  charts/kaito/workspace/templates/supported-models-configmap.yaml
  hack/compare_model_configs.sh
Labels: Review effort 4/5

#1272 docs: Update README.md with meeting notes link
  README.md
Labels: Review effort 1/5

#1274 docs: add proposal for Gateway API Inference Extension
  website/docs/proposals/20250715-inference-aware-routing-layer.md
  website/static/img/gateway-api-inference-extension.png
Labels: Review effort 3/5

#1278 chore: use tool-enabled chat templates when possible
  presets/workspace/models/llama3/model.go
  presets/workspace/models/mistral/model.go
  presets/workspace/models/phi4/model.go
  presets/workspace/models/qwen/model.go
  website/docs/tool-calling.md
  website/static/img/function-calling.gif
  website/static/img/mcp.gif
Labels: Review effort 3/5

#1275 fix: check nv plugin only for known gpu sku
  api/v1beta1/workspace_types.go
  charts/kaito/workspace/crds/kaito.sh_workspaces.yaml
  config/crd/bases/kaito.sh_workspaces.yaml
  pkg/ragengine/controllers/ragengine_controller.go
  pkg/ragengine/controllers/ragengine_controller_test.go
  pkg/utils/test/testUtils.go
  pkg/workspace/controllers/workspace_controller.go
  pkg/workspace/controllers/workspace_controller_test.go
Labels: Review effort 3/5

#1285 chore: bump local-csi-driver to v0.2.3
  charts/kaito/workspace/templates/local-csi-driver-ds.yaml
  hack/local-csi-driver-charts-sync/local-csi-driver-charts-sync.sh
  hack/local-csi-driver-charts-sync/local-csi-driver-charts.diff
Labels: Review effort 3/5

#1286 release: update manifest and helm charts for v0.5.1
  Makefile
  README.md
  charts/kaito/ragengine/Chart.yaml
  charts/kaito/ragengine/README.md
  charts/kaito/ragengine/values.yaml
  charts/kaito/workspace/Chart.yaml
  charts/kaito/workspace/README.md
  charts/kaito/workspace/values.yaml
  terraform/variables.tf
  website/docs/installation.md
  website/docs/intro.md
Labels: Review effort 2/5

#1284 refactor: introduce manifest generator -- part 1
  pkg/utils/generator/generator.go
  pkg/utils/generator/generator_test.go
  pkg/workspace/inference/preset-inferences.go
  pkg/workspace/manifests/manifests.go
  pkg/workspace/manifests/manifests_test.go
Labels: Review effort 4/5

#1248 feat: add `make help` target to Makefile
  Makefile
Labels: Review effort 2/5

#1247 docs: update installation docs to support different cloud providers
  .github/workflows/deploy-docs.yml
  Makefile
  website/docs/aws.md
  website/docs/azure.md
  website/docs/installation.md
  website/docs/quick-start.md
  website/docs/quick-start.mdx
  website/sidebars.js
  website/yarn.lock
Labels: Review effort 3/5

#1318 fix: image link error in scaler proposals
  website/docs/proposals/20250611-workspace-subresource-scale-api.md
  website/docs/proposals/20250704-keda-scaler-for-inference-workloads.md
Labels: Review effort 2/5

#1312 chore: reduce verbose logs and unnecessary reconcile
  charts/kaito/ragengine/templates/knative-logging-configmap.yaml
  charts/kaito/ragengine/values.yaml
  charts/kaito/workspace/templates/knative-logging-configmap.yaml
  charts/kaito/workspace/values.yaml
  pkg/workspace/controllers/workspace_controller.go
  pkg/workspace/controllers/workspace_controller_test.go
  pkg/workspace/controllers/workspace_gc_finalizer.go
  pkg/workspace/controllers/workspace_status.go
Labels: Review effort 4/5

#1317 fix: resolve pydantic deprecation warnings
  presets/workspace/inference/text-generation/inference_api.py
Labels: Review effort 2/5

#1314 docs: add Headlamp-KAITO to documentation
  website/docs/headlamp-kaito.md
  website/sidebars.js
  website/static/img/Headlamp.png
  website/static/img/headlamp-kaito-docs.png
  website/static/img/headlamp-kaito-plugin-installation.png
Labels: Review effort 2/5

#1327 feat: support Preferred node in RAG
  .github/workflows/ragengine-e2e-workflow.yml
  pkg/ragengine/controllers/preset-rag.go
  pkg/ragengine/controllers/preset-rag_test.go
  pkg/utils/test/testUtils.go
  test/rage2e/rag_test.go
Labels: Review effort 4/5

#1328 docs: verify docs site with Algolia
  .github/workflows/deploy-docs.yml
  website/docusaurus.config.js
Labels: Review effort 2/5
