Repository kaito-project/kaito, pull requests merged in 2025-09, with the labels that each got.

#1460 docs: fix bits of spellings and revise code of conduct for clarity
  CODE_OF_CONDUCT.md
Labels: Review effort 1/5

#1462 fix: add presets/ragengine to rag e2e test workflow
  .github/workflows/ragengine-e2e.yaml
Labels: Review effort 1/5

#1466 docs: add links and note to GPU benchmarks doc
  website/docs/gpu-benchmarks.md
Labels: Review effort 1/5

#1468 chore: bump local-csi-driver v0.2.3 -> v0.2.4 -> v0.2.5
  charts/kaito/workspace/templates/local-csi-driver-ds.yaml
  hack/local-csi-driver-charts-sync/local-csi-driver-charts-sync.sh
  hack/local-csi-driver-charts-sync/local-csi-driver-charts.diff
Labels: Review effort 2/5

#1470 release: update helm chart workflows to accept tag input from workflow_dispatch
  .github/workflows/publish-ragengine-helm-chart.yaml
  .github/workflows/publish-workspace-helm-chart.yaml
Labels: Review effort 1/5

#1412 docs: add BYO nodes redesign proposal
  docs/proposals/20250820-byo-nodes.md
Labels: Review effort 2/5

#1474 docs: add implementation strategy for BYO nodes proposal
  docs/proposals/20250820-byo-nodes.md
Labels: Review effort 1/5

#1473 feat: configure workspace replicas, perReplicaNodeCount and TargetNodeCount
  pkg/workspace/controllers/workspace_controller.go
  pkg/workspace/controllers/workspace_controller_test.go
  pkg/workspace/estimator/basicnodesestimator/estimator.go
  pkg/workspace/estimator/basicnodesestimator/estimator_test.go
Labels: Review effort 3/5

#1501 docs: Fix KAITO acronym alignment
  Makefile
  README.md
  api/v1alpha1/doc.go
  api/v1alpha1/labels.go
  api/v1beta1/labels.go
  charts/kaito/ragengine/values.yaml
  charts/kaito/workspace/values.yaml
  docs/documentation-versioning.md
  docs/proposals/20250611-workspace-subresource-scale-api.md
  docs/proposals/20250630-kaito-cli.md
  examples/custom-model-integration/Dockerfile.reference
  examples/custom-model-integration/reference-image-deployment.yaml
  pkg/featuregates/featuregates.go
  pkg/model/interface.go
  pkg/utils/plugin/plugin.go
  test/e2e/inference_with_adapters_test.go
  test/e2e/preset_test.go
  test/e2e/preset_vllm_test.go
  test/rage2e/rag_test.go
  website/docs/usage.md
Labels: Review effort 1/5

#1510 fix: helm upgrade --install needs release name
  website/docs/installation.md
  website/docs/rag.md
Labels: Review effort 1/5

#1507 feat: Max token calculator
  api/v1beta1/inference_config_validation.go
  api/v1beta1/workspace_validation.go
  api/v1beta1/workspace_validation_test.go
  pkg/model/interface.go
  pkg/utils/config_parser.go
  pkg/utils/test/test_model.go
  pkg/utils/test/test_utils.go
  pkg/workspace/controllers/workspace_controller.go
  pkg/workspace/controllers/workspace_controller_test.go
  pkg/workspace/estimator/advancednodesestimator/estimator.go
  pkg/workspace/estimator/advancednodesestimator/estimator_test.go
  pkg/workspace/estimator/basicnodesestimator/estimator.go
  pkg/workspace/estimator/basicnodesestimator/estimator_test.go
  pkg/workspace/estimator/interfaces.go
  pkg/workspace/inference/max_model_len_strategy.go
  pkg/workspace/inference/max_model_len_strategy_test.go
  pkg/workspace/inference/preset_inferences.go
  pkg/workspace/inference/preset_inferences_test.go
  presets/workspace/models/deepseek/model.go
  presets/workspace/models/falcon/model.go
  presets/workspace/models/gpt/model.go
  presets/workspace/models/llama3/model.go
  presets/workspace/models/mistral/model.go
  presets/workspace/models/phi2/model.go
  presets/workspace/models/phi3/model.go
  presets/workspace/models/phi4/model.go
  presets/workspace/models/qwen/model.go
  sku-calculation/calculate_model_weight_and_bytes_per_token.py
  sku-calculation/model-sku-calculation.md
  test/e2e/preset_test.go
  test/e2e/preset_vllm_test.go
Labels: Review effort 4/5

#1503 docs: Introduce a new InferenceSet CRD and Controller for scaling inference workloads automatically
  docs/proposals/20250918-introduce_inferenceset_autoscaling.md
Labels: Review effort 2/5

#1534 docs: Update rag.md
  website/docs/rag.md
Labels: Review effort 1/5
