Repository kaito-project/kaito, pull requests merged in 2025-06, with the labels that each got.

#1155 test: Exclude gpu-provisioner check in case of running e2e on managed mode
  test/e2e/e2e_test.go
  test/e2e/inference_with_adapters_test.go
  test/e2e/preset_test.go
  test/e2e/preset_vllm_test.go
  test/rage2e/e2e_test.go
  test/rage2e/rag_test.go
Labels: tests

#1139 test: add support volume for tuning e2e
  api/v1alpha1/workspace_validation.go
  api/v1alpha1/workspace_validation_test.go
  api/v1beta1/workspace_validation.go
  api/v1beta1/workspace_validation_test.go
  test/e2e/preset_test.go
  test/e2e/utils/utils.go
Labels: Review effort 4/5

#1164 feat: RAG metrics part 2
  presets/ragengine/main.py
  presets/ragengine/metrics/prometheus_metrics.py
Labels: Review effort 4/5

#1175 feat: update rag engine image url to be build from env
  charts/kaito/ragengine/templates/deployment.yaml
  charts/kaito/ragengine/values.yaml
  pkg/ragengine/controllers/preset-rag.go
  pkg/ragengine/controllers/preset-rag_test.go
Labels: Review effort 3/5

#1169 docs: add proposal for Distributing LLM Model Files as OCI Artifacts
  docs/img/model-as-oci-artifacts-evaluation.png
  docs/proposals/20250609-model-as-oci-artifacts.md
Labels: Review effort 3/5

#1177 fix: require max-model-len for distributed inference
  api/v1alpha1/inference_config_validation.go
  api/v1alpha1/workspace_validation.go
  api/v1alpha1/workspace_validation_test.go
  api/v1beta1/inference_config_validation.go
  api/v1beta1/workspace_validation.go
  api/v1beta1/workspace_validation_test.go
  test/e2e/preset_test.go
Labels: Review effort 4/5

#1173 perf: distribute model as oci artifacts
  .github/actions/build-image-action/action.yml
  .github/determine_models.py
  .github/workflows/e2e-preset-test.yml
  .github/workflows/kind-cluster/docker-job-template.yaml
  .github/workflows/kind-cluster/kind-1es.yaml
  .github/workflows/kind-cluster/kind.yaml
  .github/workflows/kind-cluster/main.py
  .github/workflows/preset-image-build-1ES.yml
  .github/workflows/preset-image-build.yml
  docker/presets/models/tfs/Dockerfile
  docker/presets/models/tfs/README.md
  docker/presets/models/tfs/download_and_push_model.py
Labels: Review effort 4/5

#1182 feat: adding CURL E2E tests for update/delete doc and delete index
  .github/workflows/ragengine-e2e-workflow.yml
  Makefile
  presets/ragengine/tests/vector_store/test_base_store.py
  presets/ragengine/vector_store/base.py
  test/rage2e/rag_test.go
Labels: Review effort 4/5

#1187 fix: adapt to vllm 0.9.0
  presets/workspace/inference/vllm/inference_api.py
Labels: Review effort 3/5

#1196 docs: fix broken links for presets
  website/docs/presets.md
Labels: Review effort 2/5

#1184 docs: add proposal for supporting scale subresource api of workspace
  website/docs/proposals/20250611-workspace-subresource-scale-api.md
  website/static/img/workspace-controller-workflow.png
  website/static/img/workspace-scale-api.png
  website/static/img/workspace-webhook-for-create-req.png
  website/static/img/workspace-webhook-for-scale-req.png
Labels: Review effort 3/5

#1205 Skip automatic gpu driver installation GA doc update
  website/docs/kaito-on-byo-gpu-nodes.md
Labels: Review effort 2/5

#1204 feat: Add RagEngine README.md
  charts/kaito/ragengine/README.md
Labels: Review effort 2/5

#1218 feat: Create artifacthub-repo.yml
  charts/kaito/artifacthub-repo.yml
Labels: Review effort 2/5

#1194 chore: converge Errors and update tests
  presets/ragengine/main.py
  presets/ragengine/metrics/prometheus_metrics.py
  presets/ragengine/tests/api/test_main.py
  presets/ragengine/vector_store/base.py
Labels: Review effort 4/5

#1221 fix: update helm chart URLs to point to kaito-project instead of Azure
  charts/kaito/index.yaml
Labels: Review effort 2/5
