Repository kaito-project/kaito, pull requests merged in 2025-04, with the labels that each got.

#967 Update README.md for RAG coming soon
  README.md
Labels: Review effort 1/5

#969 Update README.md
  README.md
Labels: Review effort 1/5

#964 fix: add dependencies for vllm runtime
  .github/workflows/e2e-preset-test.yml
  .github/workflows/e2e-preset-tuning-test.yml
  docker/presets/models/tfs/Dockerfile
  presets/workspace/dependencies/requirements.txt
Labels: Review effort 2/5

#968 chore: RAG quickstart
  docs/RAG/RAGEngine-installation.md
  docs/RAG/README.md
  examples/RAG/kaito_ragengine_phi_3.yaml
Labels: Review effort 2/5

#971 fix: Pin disable chunked prefill on V100 Arch
  presets/workspace/inference/vllm/inference_api.py
Labels: Review effort 2/5

#978 feat: Add Phi-4 and Qwen 32B models
  examples/inference/kaito_workspace_phi_4.yaml
  examples/inference/kaito_workspace_phi_4_mini.yaml
  examples/inference/kaito_workspace_qwen_2.5_coder_32b-instruct.yaml
  presets/workspace/models/phi4/README.md
  presets/workspace/models/phi4/model.go
  presets/workspace/models/qwen/README.md
  presets/workspace/models/qwen/model.go
Labels: Review effort 2/5

#980 feat: Add Pytorch Expandable segments envvar
  pkg/workspace/manifests/manifests.go
  presets/workspace/models/qwen/model.go
Labels: Review effort 2/5

#985 docs: Update reference-image-deployment.yaml
  docs/custom-model-integration/reference-image-deployment.yaml
Labels: Review effort 2/5

#981 test: add more model preset testing config
  .github/e2e-preset-configs.json
  .github/matrix-configs.json
  .github/workflows/e2e-base-setup.yaml
  .github/workflows/e2e-preset-test.yml
  .github/workflows/helm-chart.yml
  .github/workflows/lint-go.yml
  .github/workflows/markdown-link-check.yml
  .github/workflows/pr-title-lint.yml
  .github/workflows/publish-workspace-mcr-image.yml
  .github/workflows/unit-tests.yml
  .github/workflows/workspace-e2e.yml
  Makefile
  presets/workspace/test/manifests/inference-tmpl/manifest.yaml
Labels: Review effort 4/5

#987 docs: add custom config usage guide
  docs/inference/README.md
  examples/inference/kaito_workspace_custom_config.yaml
Labels: Review effort 2/5

#986 feat: Add Annotation Bypass GPU Mem check
  api/v1alpha1/labels.go
  api/v1alpha1/workspace_validation.go
  api/v1alpha1/workspace_validation_test.go
  api/v1beta1/labels.go
  api/v1beta1/workspace_validation.go
  api/v1beta1/workspace_validation_test.go
  examples/README.md
Labels: Review effort 3/5

#996 feat: Add controller tags
  Makefile
  presets/workspace/models/deepseek/model.go
  presets/workspace/models/falcon/model.go
  presets/workspace/models/mistral/model.go
  presets/workspace/models/phi2/model.go
  presets/workspace/models/phi3/model.go
  presets/workspace/models/qwen/model.go
Labels: Review effort 2/5

#979 feat: Enhance vLLM Configuration Validation
  Makefile
  api/v1alpha1/inference_config_validation.go
  api/v1alpha1/tuning_config_validation.go
  api/v1alpha1/workspace_validation.go
  api/v1alpha1/workspace_validation_test.go
  api/v1beta1/inference_config_validation.go
  api/v1beta1/tuning_config_validation.go
  api/v1beta1/workspace_validation.go
  api/v1beta1/workspace_validation_test.go
  api/v1beta1/zz_generated.deepcopy.go
  test/e2e/preset_test.go
  test/e2e/webhook_test.go
Labels: Review effort 4/5

#1002 chore: refactor interface.go
  pkg/model/interface.go
  pkg/utils/test/testModel.go
  pkg/workspace/inference/preset-inferences.go
  pkg/workspace/inference/preset-inferences_test.go
Labels: Review effort 2/5

#1008 fix: allow backoff for tuning job
  pkg/workspace/manifests/manifests.go
Labels: Review effort 2/5

#1015 feat: Provide default chat templates for Falcon and Phi-2 fine-tuning
  presets/workspace/models/falcon/model.go
  presets/workspace/models/phi2/model.go
Labels: Review effort 2/5

#1021 docs: update vllm 0.8.2 metrics
  docs/inference/Monitoring.md
Labels: Review effort 2/5

#1018 docs: Enhance README with fine-tuning config details
  charts/kaito/workspace/templates/lora-params.yaml
  charts/kaito/workspace/templates/qlora-params.yaml
  presets/workspace/models/falcon/README.md
  presets/workspace/models/phi2/README.md
Labels: Review effort 2/5

#1016 docs: OOM prevention mechanisms used in Kaito
  docs/img/gpumemlayout.png
  docs/kaito-oom-prevention.md
Labels: Review effort 2/5

#1020 feat: Add workload count metrics for kaito workspace
  pkg/workspace/controllers/metrics.go
  pkg/workspace/controllers/workspace_controller.go
Labels: Review effort 3/5

#1024 release: update manifest and helm charts for v0.4.5
  Makefile
  charts/kaito/workspace/Chart.yaml
  charts/kaito/workspace/README.md
  charts/kaito/workspace/values.yaml
  docs/installation.md
Labels: Review effort 2/5

#1028 fix: add registry into release pipeline (#1026)
  .github/workflows/e2e-workflow.yml
Labels: Review effort 2/5

#1029 chore: doc for workspace controller metrics
  docs/controller-metrics/kaito-workspace_controller_metrics.md
Labels: Review effort 1/5

#1032 feat: add base image build target in Dockerfile
  .github/actions/build-image-action/action.yml
  .github/workflows/kind-cluster/determine_models.py
  .github/workflows/kind-cluster/docker-job-template.yaml
  .github/workflows/kind-cluster/main.py
  .github/workflows/preset-image-build-1ES.yml
  .github/workflows/preset-image-build.yml
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.deepcopy.go
  docker/presets/models/tfs/Dockerfile
  presets/workspace/models/supported_models.yaml
Labels: Review effort 4/5

#1046 feat: Add more fine-tuning examples
  examples/fine-tuning/kaito_workspace_tuning_falcon_7b_mental.yaml
  examples/fine-tuning/kaito_workspace_tuning_falcon_7b_oai.yaml
Labels: Review effort 2/5

#1044 feat: parse supported_models.yaml in plugin pkg before starting manager
  .github/workflows/license-header.yml
  Tiltfile
  cmd/workspace/models.go
  docker/workspace/Dockerfile
  go.mod
  pkg/model/interface.go
  pkg/ragengine/manifests/manifests_test.go
  pkg/utils/common_test.go
  pkg/utils/plugin/plugin.go
  pkg/utils/test/mockClient.go
  pkg/workspace/controllers/workspace_gc_finalizer_test.go
  pkg/workspace/tuning/preset-tuning-types.go
  pkg/workspace/tuning/preset-tuning.go
  presets/workspace/models/metadata.go
  test/rage2e/rag_test.go
Labels: Review effort 4/5

#1045 feat: Ensure latest security patches applied on debian packages
  docker/presets/models/llama-2/Dockerfile
  docker/presets/models/tfs/Dockerfile
  docker/ragengine/service/Dockerfile
Labels: Review effort 2/5

#1055 chore: update RAG doc for avoiding conflicts
  docs/RAG/README.md
  examples/RAG/kaito_ragengine_phi_3.yaml
Labels: Review effort 2/5

#1057 fix: only add finalizer when the object is not in deletion state
  pkg/ragengine/controllers/ragengine_controller.go
  pkg/ragengine/controllers/ragengine_gc_finalizer.go
  pkg/workspace/controllers/workspace_controller.go
  pkg/workspace/controllers/workspace_gc_finalizer.go
Labels: Review effort 2/5

#1058 fix: should not check preset model in sync loop
  pkg/workspace/controllers/workspace_controller.go
Labels: Review effort 2/5

#1049 chore: avoid using goto by using retry.OnError
  pkg/ragengine/controllers/ragengine_controller.go
  pkg/utils/nodeclaim/nodeclaim.go
  pkg/utils/nodeclaim/nodeclaim_test.go
  pkg/utils/resources/nodes.go
  pkg/workspace/controllers/workspace_controller.go
Labels: Review effort 3/5

#1075 chore: add license header check for Python files
  .github/workflows/kind-cluster/determine_models.py
  .github/workflows/kind-cluster/main.py
  .github/workflows/license-header.yml
  demo/inferenceUI/chainlit_openai.py
  demo/inferenceUI/chainlit_transformers.py
  docker/presets/models/tfs-onnx/convert_to_onnx.py
  presets/ragengine/__init__.py
  presets/ragengine/embedding/__init__.py
  presets/ragengine/inference/__init__.py
  presets/ragengine/tests/__init__.py
  presets/ragengine/tests/api/__init__.py
  presets/ragengine/tests/vector_store/__init__.py
  presets/ragengine/vector_store/__init__.py
  presets/ragengine/vector_store_manager/__init__.py
  presets/workspace/inference/text-generation/tests/test_inference_api.py
  presets/workspace/inference/text-generation/tests/test_model_config.py
  presets/workspace/inference/vllm/tests/test_vllm_inference_api.py
  presets/workspace/test/scripts/generate_manifests.py
Labels: Review effort 3/5

#1071 fix: ragengine index document returns wrong ids
  presets/ragengine/tests/vector_store/test_base_store.py
  presets/ragengine/vector_store/base.py
Labels: Review effort 3/5

#1074 refactor: remove fields from PresetParam in favor of embedded Metadata
  api/v1alpha1/workspace_validation.go
  api/v1beta1/workspace_validation.go
  pkg/model/interface.go
  pkg/workspace/tuning/preset-tuning_test.go
  presets/workspace/models/deepseek/model.go
  presets/workspace/models/falcon/model.go
  presets/workspace/models/llama2/model.go
  presets/workspace/models/llama2chat/model.go
  presets/workspace/models/metadata.go
  presets/workspace/models/mistral/model.go
  presets/workspace/models/phi2/model.go
  presets/workspace/models/phi3/model.go
  presets/workspace/models/phi4/model.go
  presets/workspace/models/qwen/model.go
Labels: Review effort 4/5

#1048 chore: simplify the manifests generation code and add ut
  pkg/ragengine/controllers/preset-rag.go
  pkg/ragengine/controllers/ragengine_controller.go
  pkg/ragengine/manifests/manifests.go
  pkg/ragengine/manifests/manifests_test.go
  pkg/utils/test/testUtils.go
  pkg/workspace/controllers/workspace_controller.go
  pkg/workspace/inference/preset-inferences.go
  pkg/workspace/inference/template_inference.go
  pkg/workspace/manifests/manifests.go
  pkg/workspace/manifests/manifests_test.go
  pkg/workspace/tuning/preset-tuning.go
Labels: Review effort 3/5

#1080 fix: document id's on list document responses are the same as document id's on create document responses
  presets/ragengine/tests/api/test_main.py
  presets/ragengine/tests/vector_store/test_base_store.py
  presets/ragengine/vector_store/base.py
Labels: Review effort 3/5

#1079 fix: guard nodeclass op by featuregate
  charts/kaito/workspace/crds/karpenter.azure.com_aksnodeclasses.yaml
  cmd/workspace/main.go
  pkg/utils/nodeclaim/nodeclaim.go
Labels: Review effort 3/5

#1047 test: add trivy action to scan CVE
  .github/workflows/trivy.yml
Labels: Review effort 2/5

#1035 feat: support preset model weight downloads
  api/v1beta1/workspace_types.go
  api/v1beta1/workspace_validation.go
  api/v1beta1/workspace_validation_test.go
  charts/kaito/workspace/crds/kaito.sh_workspaces.yaml
  config/crd/bases/kaito.sh_workspaces.yaml
  pkg/model/interface.go
  pkg/utils/common.go
  pkg/utils/common_test.go
  pkg/utils/test/testModel.go
  pkg/utils/test/testUtils.go
  pkg/workspace/inference/preset-inferences.go
  pkg/workspace/inference/preset-inferences_test.go
  pkg/workspace/manifests/manifests.go
  pkg/workspace/manifests/manifests_test.go
  presets/workspace/models/metadata.go
  presets/workspace/models/metadata_test.go
Labels: Review effort 4/5

#1070 fix: ensureNodePlugins does not work
  pkg/ragengine/controllers/ragengine_controller.go
  pkg/ragengine/controllers/ragengine_controller_test.go
  pkg/utils/resources/nodes.go
  pkg/utils/resources/nodes_test.go
  pkg/workspace/controllers/workspace_controller.go
  pkg/workspace/controllers/workspace_controller_test.go
Labels: Review effort 3/5
